config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'homes#index'

  resources :courses do
    member do
      get :select
      get :quit
      get :open
      get :close
    end
    collection do
      get :scorecount
      get :timetable
      get :list
      post :list
    end
  end

  resources :grades, only: [:index, :update]
  resources :users

  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'

end

app/views/layouts/_content.html.erb
<br>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong> <%= message %></strong>
      </div>
  <% end %>
</div>

<%= yield %>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <footer class="container-fluid">
    <p class="text-center">中国科学院大学版权所有 © 2016
    </p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <%= link_to "CourseSelect", root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

        <li class=<%= "active" if params[:controller]=="homes" %>> <%= link_to "主页", root_path %></li>

        <% if student_logged_in? %>
            <li class=<%= "active" if params[:controller]=="courses" %>> <%= link_to "我的课程", courses_path %></li>
        <% elsif teacher_logged_in? %>
            <li class=<%= "active" if params[:controller]=="courses" %>> <%= link_to "课程管理", courses_path %></li>
        <% elsif admin_logged_in? %>
            <li> <%= link_to "控制面板", rails_admin_path %></li>
        <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
            <li>
              <%= link_to edit_user_path(current_user) do %>
                  <%= current_user.name %><span class="glyphicon glyphicon-user"></span>
              <% end %>
            </li>

            <li>
              <p class="navbar-text"><%= current_user.department %></p>
            </li>

            <li>
              <%= link_to sessions_logout_path, method: :delete do %>
                  退出 <span class="	glyphicon glyphicon-off"></span>
              <% end %>
            </li>

        <% else %>

            <li><%= link_to sessions_login_path do %>
                  登陆 <span class="	glyphicon glyphicon-user"></span>
              <% end %>
            </li>

            <li><%= link_to new_user_path do %>
                  注册 <span class="	glyphicon glyphicon-log-in"></span>
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseSelect</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta>
  <meta name="renderer" content="webkit">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= csrf_meta_tags %>
</head>

<body class="<%= "body-background" if params[:controller]!="homes" %>">

<%= render partial: 'layouts/header' %>
<%= render partial: 'layouts/content' %>
<%= render partial: 'layouts/footer' %>

</body>
</html>